name: CI

on:
  push:

jobs:
  marinates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - uses: blairhudson/jupydiff@master #hello? no yes? yeeeees
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#
