name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: blairhudson/jupydiff@master #hell
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#
